#namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: micro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-imagen-deployment
spec:
  selector:
    matchLabels:
      app: micro-imagen
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-imagen
    spec:
      containers:
        - name: micro-imagen
          image: trion97/test:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-imagen-clusterip
spec:
  ports:
    - protocol: "TCP"
      port: 8082        # The port inside the cluster
      targetPort: 8082  # The port exposed by the service
  type: LoadBalancer        # Type of service
  selector:
    app: micro-imagen

