pipeline {
    agent any
    tools {
        gradle 'Gradle 7.5.1' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'gradle task'
                sh 'gradle init'
                sh 'gradle wrapper'
                sh './gradlew build'
                //sh 'gradle assemble'
            }
        }
        stage('test') {
            steps {
                //sh 'gradle docker'
                echo 'test succesfull'
            }
        }
        stage('Build Docker Image') {
            steps {
                //sh 'gradle docker'
                echo 'succesfull'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_hub', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                     sh 'docker push myimage:latest'
                }
        stage('push Docker Image') {
            steps {
                //sh 'gradle dockerRun'
                echo 'succesfull'
            }
        }
    }
}

